### ISSUE TITLE
使用大猫猫的节点脚本安装以后，显示IP无效？是什么原因呢？

### ISSUE THREAD

**Issue by SHctt** [Anankke/shadowsocks-mod#30]
INFO: loading config from user-config.json
2021-12-30 11:36:47 INFO     util.py:47 loading libcrypto from libcrypto.so.1.1
2021-12-30 11:36:47 INFO     asyncdns.py:323 dns server: [('23.238.23.23', 53), ('23.238.25.25', 53), ('1.1.1.1', 53), ('8.8.8.8', 53)]
2021-12-30 11:36:47 INFO     asyncdns.py:323 dns server: [('23.238.23.23', 53), ('23.238.25.25', 53), ('1.1.1.1', 53), ('8.8.8.8', 53)]
2021-12-30 11:36:47 ERROR    webapi_utils.py:41 Wrong data: IP is invalid. Now, your IP address is 2a0d:7c40:3000:bcb::2
2021-12-30 11:36:47 ERROR    web_transfer.py:543 Traceback (most recent call last):
  File "/soft/shadowsocks/web_transfer.py", line 529, in thread_db
    ping = webapi.getApi("func/ping")
  File "/soft/shadowsocks/webapi_utils.py", line 42, in getApi
    raise Exception('Server Error!')
Exception: Server Error!

**Comment by ghost** [comment]
@SHctt Exception: Server Error!

**Comment by jameqq** [comment]
借楼问一下 用脚本对接单端口后
![image](https://user-images.githubusercontent.com/25794322/147749354-b45e4de7-3300-4bda-9c39-65e3216b33c1.png)
提示这个 端口不能正常打开是什么问题

**Comment by Anankke** [comment]
> INFO: loading config from user-config.json 2021-12-30 11:36:47 INFO util.py:47 loading libcrypto from libcrypto.so.1.1 2021-12-30 11:36:47 INFO asyncdns.py:323 dns server: [('23.238.23.23', 53), ('23.238.25.25', 53), ('1.1.1.1', 53), ('8.8.8.8', 53)] 2021-12-30 11:36:47 INFO asyncdns.py:323 dns server: [('23.238.23.23', 53), ('23.238.25.25', 53), ('1.1.1.1', 53), ('8.8.8.8', 53)] 2021-12-30 11:36:47 ERROR webapi_utils.py:41 Wrong data: IP is invalid. Now, your IP address is 2a0d:7c40:3000:bcb::2 2021-12-30 11:36:47 ERROR web_transfer.py:543 Traceback (most recent call last): File "/soft/shadowsocks/web_transfer.py", line 529, in thread_db ping = webapi.getApi("func/ping") File "/soft/shadowsocks/webapi_utils.py", line 42, in getApi raise Exception('Server Error!') Exception: Server Error!

希望所有人都有个不懂英语但是也会开翻译的脑子
