### ISSUE TITLE
ERROR    webapi_utils.py:73 Wrong data: {"ret":0} ERROR    web_transfer.py:543 Traceback (most recent call last):

### ISSUE THREAD

**Issue by 192255** [Anankke/shadowsocks-mod#44]
ERROR    webapi_utils.py:73 Wrong data: {"ret":0}
ERROR    web_transfer.py:543 Traceback (most recent call last):
  File "/root/panel/shadowsocks-mod-3.5.1/web_transfer.py", line 535, in thread_db
    db_instance.push_db_all_user()
  File "/root/panel/shadowsocks-mod-3.5.1/web_transfer.py", line 158, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/panel/shadowsocks-mod-3.5.1/web_transfer.py", line 62, in update_all_user
    "users/traffic", {"node_id": get_config().NODE_ID}, {"data": data}
  File "/root/panel/shadowsocks-mod-3.5.1/webapi_utils.py", line 74, in postApi
    raise Exception('Server Error!')

**Comment by 192255** [comment]
ERROR    web_transfer.py:543 Traceback (most recent call last):
  File "/root/panel/shadowsocks-mod-3.5.1/web_transfer.py", line 538, in thread_db
    last_rows, rows
  File "/root/panel/shadowsocks-mod-3.5.1/web_transfer.py", line 230, in del_server_out_of_bound_safe
    if row["is_multi_user"] != 0:
KeyError: 'is_multi_user'

**Comment by ghost** [comment]
Please consider using other modern Shadowsocks servers with AEAD & 2022 encryption support for example XrayR or soga, this python implementation of the ShadowsocksR server is outdated and has security issues. If you insist on using this server for whatever reason, you must install an old version of SSPanel-UIM(2022.11 or older) to be fully compatible with this server.
